FROM eclipse-temurin:17

LABEL maintainer = "shambhavik24"

WORKDIR /app


COPY target/springboot-restful-docker-0.0.1-SNAPSHOT.jar /app/springboot-restful-docker.jar

ENTRYPOINT ["java" , "-jar", "springboot-restful-docker.jar" ]








